//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class allowance_summary
    {
        public string PERSON_ID { get; set; }
        public string PAY_CODE { get; set; }
        public string PAY_CODE_DESC { get; set; }
        public decimal AMT { get; set; }
        public System.DateTime START_DATE { get; set; }
        public string CURRENCY_CODE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public Nullable<decimal> FREQUENCY { get; set; }
        public string IS_ONCE { get; set; }
    }
}
