//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_configuration
    {
        public System.Guid GID { get; set; }
        public string CODE { get; set; }
        public string SmtpHost { get; set; }
        public string SmtpPort { get; set; }
        public string EmailAddress { get; set; }
        public string EmailPass { get; set; }
    }
}
