//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel_info
    {
        public string PERSON_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string CHINESE_NAME { get; set; }
        public string ALIAS_NAME { get; set; }
        public string PERS_MOBILE { get; set; }
        public string COMPANY { get; set; }
        public string PERS_EMAIL { get; set; }
        public string NATIONAL_ID { get; set; }
        public Nullable<System.DateTime> LASTEST_HIRE_DATE { get; set; }
        public Nullable<double> SAL_AMT { get; set; }
        public string POSITION_TITLE { get; set; }
        public string WORK_LOCATION { get; set; }
        public string COST_CENTER { get; set; }
        public string ACTION { get; set; }
        public Nullable<System.DateTime> LAST_EMP_DATE { get; set; }
        public string TERM_REASON { get; set; }
        public string STATUS { get; set; }
        public string WORKER_TYPE { get; set; }
        public Nullable<System.DateTime> SYS_CREATE_DATE { get; set; }
        public string COST_CENTER_DESC { get; set; }
    }
}
